name: .NET
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:

  build:
    runs-on: ${{matrix.os}}
    strategy: 
      matrix: 
        os: [ubuntu-latest]
        dotnet-version: [6.0.x]
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Setup .NET
      uses: actions/setup-dotnet@main
      with:
        dotnet-version:  ${{matrix.dotnet-version}}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: dotnet test
      run: dotnet test
  publish:
    need: build
    runs-on: ${{matrix.os}}
    strategy: 
      matrix: 
        os: [ubuntu-latest]
        dotnet-version: [6.0.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Setup .Net
        uses: actions/setup-dotnet@main

      - name: Nuget Package And Upload
        uses: csharp-opensource/publish-nuget@master
        with:
          releaseVersion: ${{ github.event.release.tag_name }}
          repoUrl: ${{ github.server_url }}/${{ github.repository }}
          nugetToken: ${{ secrets.NUGET_AUTH_TOKEN }}
          nugetSource: https://api.nuget.org/v3/index.json
