name: .NET
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  update_release_draft:
      runs-on: ubuntu-latest
      steps:
        # (Optional) GitHub Enterprise requires GHE_HOST variable set
        #- name: Set GHE_HOST
        #  run: |
        #    echo "GHE_HOST=${GITHUB_SERVER_URL##https:\/\/}" >> $GITHUB_ENV

        # Drafts your next Release notes as Pull Requests are merged into "master"
        - uses: release-drafter/release-drafter@v5
          # (Optional) specify config name to use, relative to .github/. Default: release-drafter.yml
          # with:
          #   config-name: my-config.yml
          #   disable-autolabeler: true
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build:
    runs-on: ${{matrix.os}}
    strategy: 
      matrix: 
        os: [ubuntu-latest]
        dotnet-version: [6.0.x]
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Setup .NET
      uses: actions/setup-dotnet@main
      with:
        dotnet-version:  ${{matrix.dotnet-version}}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: dotnet test
      run: dotnet test
  publish:
    needs: build
    runs-on: ${{matrix.os}}
    strategy: 
      matrix: 
        os: [ubuntu-latest]
        dotnet-version: [6.0.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: run file
        run: echo ${{ github.server_url }}/${{ github.repository }}
      - name: Setup .Net
        uses: actions/setup-dotnet@main
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Build
        run: dotnet publish
      - name: Nuget Package And Upload
        uses: csharp-opensource/publish-nuget@master
        with:
          releaseVersion: ${{ github.event.release.tag_name }}
          repoUrl: ${{ github.server_url }}/${{ github.repository }}
          nugetToken: ${{ secrets.NUGET_AUTH_TOKEN }}
          nugetSource: https://api.nuget.org/v3/index.json
