name: .NET
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:

  build:
    runs-on: ${{matrix.os}}
    strategy: 
      matrix: 
        os: [ubuntu-latest, windows-latest]
        dotnet-version: [6.0.x]
    steps:
    - name: get env name
      run: echo ${{ runner.os }}
    - name: Cache NPM dependencies
      uses: actions/cache@v2
      with:
       path: ~/.npm
       key: ${{ runner.os }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
       restore-keys: |
        ${{ runner.os }}-npm-cache-
    - name:  run script
      if: ${{runner.os}} == 'Linux'
      run: ./.github/workflows/script.sh
      shell: bash
    - name: when windows
      if: ${{ runner.os }} == 'windows-latest'
      run: dir
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version:  ${{matrix.dotnet-version}}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: dotnet publish
      run: dotnet publish
    
